apiVersion: v1
kind: Secret
metadata:
  name: travel-app-secret
  namespace: travel-app
type: Opaque
stringData:
  DATABASE_URL: postgresql://travel_user:strongpassword@postgres:5432/travel_blueprint
  NEXTAUTH_SECRET: "JZQVeEJMkdPaSVNY0GkuXrQiTLaluNozmJ1UF/dfJNg="
  NEXTAUTH_URL: http://localhost
  B2_KEY_ID: 05c4c500ccbc8b0000000001
  B2_APPLICATION_KEY: K005W1FRzLFhv+mBtr6rbuUczZK0y00
  B2_BUCKET_NAME: travel-blueprint-prod
  B2_ENDPOINT: https://s3.us-east-005.backblazeb2.com
  B2_REGION: us-east-005