apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: travel-app
type: Opaque
stringData:
  POSTGRES_USER: travel_user
  POSTGRES_PASSWORD: strongpassword
  POSTGRES_DB: travel_blueprint